### ISSUE TITLE
Lutris 5.0 fails to launch wine

### ISSUE THREAD

**Issue by IanTrudel** [jatin-cbs/Lutris-RHEL-CentOS7#4]
Something is just not right. Lutris won't launch anything. For example, launching Wine Steam results into the following error.

```
Running /home/ian/.local/share/lutris/runners/wine/tkg-4.1-x86_64/bin/wine /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/Steam.exe -no-cef-sandbox -console
Traceback (most recent call last):
  File "/usr/bin/lutris-wrapper", line 126, in <module>
    main()
  File "/usr/bin/lutris-wrapper", line 102, in main
    returncode = subprocess.run(args).returncode
AttributeError: 'module' object has no attribute 'run'
```

Full log:
```
INFO     2019-03-29 17:23:07,784 [application.do_command_line:219]:Running Lutris 0.5.1.2
INFO     2019-03-29 17:23:07,785 [startup.check_driver:55]:Using NVIDIA drivers 418.30 for x86_64
INFO     2019-03-29 17:23:07,785 [startup.check_driver:59]:GPU: GeForce GTX 660M
INFO     2019-03-29 17:23:07,786 [startup.check_driver:76]:GPU: 10DE:0FD4 1043:2115 using nvidia drivers
INFO     2019-03-29 17:23:07,842 [startup.check_vulkan:113]:Vulkan is supported
INFO     2019-03-29 17:23:07,843 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
INFO     2019-03-29 17:23:08,128 [lutriswindow.toggle_connection:561]:Connected to lutris.net as IanTrudel
DEBUG    2019-03-29 17:23:08,132 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2019-03-29 17:23:08,139 [http.get:68]:GET https://lutris.net/api/games/library/IanTrudel
INFO     2019-03-29 17:23:11,512 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/system32/dxgi with DXVK version
INFO     2019-03-29 17:23:11,513 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/system32/d3d11 with DXVK version
INFO     2019-03-29 17:23:11,513 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/system32/d3d10core with DXVK version
INFO     2019-03-29 17:23:11,513 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/system32/d3d10_1 with DXVK version
INFO     2019-03-29 17:23:11,514 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/system32/d3d10 with DXVK version
INFO     2019-03-29 17:23:11,514 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/syswow64/dxgi with DXVK version
INFO     2019-03-29 17:23:11,514 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/syswow64/d3d11 with DXVK version
INFO     2019-03-29 17:23:11,514 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/syswow64/d3d10core with DXVK version
INFO     2019-03-29 17:23:11,515 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/syswow64/d3d10_1 with DXVK version
INFO     2019-03-29 17:23:11,515 [dxvk.enable_dxvk_dll:123]:Replacing /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/windows/syswow64/d3d10 with DXVK version
DEBUG    2019-03-29 17:23:11,515 [system.execute:38]:Executing pgrep Steam.exe$
DEBUG    2019-03-29 17:23:11,538 [command.start:105]:Running /usr/bin/lutris-wrapper 0 0 /home/ian/.local/share/lutris/runners/wine/tkg-4.1-x86_64/bin/wine /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/Steam.exe -no-cef-sandbox -console
DEBUG    2019-03-29 17:23:11,539 [command.start:107]:ENV: LD_LIBRARY_PATH="/home/ian/.local/share/lutris/runners/wine/tkg-4.1-x86_64/lib:/home/ian/.local/share/lutris/runners/wine/tkg-4.1-x86_64/lib64:/lib:/lib64:/usr/lib:/usr/lib64:/home/ian/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/ian/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/ian/.local/share/lutris/runtime/steam/i386/lib:/home/ian/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/ian/.local/share/lutris/runtime/steam/i386/usr/lib:/home/ian/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/ian/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/ian/.local/share/lutris/runtime/steam/amd64/lib:/home/ian/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/ian/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    2019-03-29 17:23:11,539 [command.start:107]:ENV: STEAM_RUNTIME="/home/ian/.local/share/lutris/runtime/steam"
DEBUG    2019-03-29 17:23:11,539 [command.start:107]:ENV: WINEDEBUG="-all"
DEBUG    2019-03-29 17:23:11,539 [command.start:107]:ENV: WINEARCH="win64"
DEBUG    2019-03-29 17:23:11,539 [command.start:107]:ENV: PYTHONPATH="/usr/bin:/usr/lib64/python34.zip:/usr/lib64/python3.4:/usr/lib64/python3.4/plat-linux:/usr/lib64/python3.4/lib-dynload:/usr/lib64/python3.4/site-packages:/usr/lib/python3.4/site-packages:/usr/lib/python3.4/site-packages/evdev-1.1.2-py3.4-linux-x86_64.egg"
DEBUG    2019-03-29 17:23:11,539 [command.start:107]:ENV: WINEESYNC="1"
DEBUG    2019-03-29 17:23:11,539 [command.start:107]:ENV: WINE="/home/ian/.local/share/lutris/runners/wine/tkg-4.1-x86_64/bin/wine"
DEBUG    2019-03-29 17:23:11,540 [command.start:107]:ENV: WINEPREFIX="/home/ian/.local/share/lutris/runners/winesteam/prefix64"
DEBUG    2019-03-29 17:23:11,544 [signals.register_handler:26]:Registering <bound method MonitoredCommand.on_stop of <lutris.command.MonitoredCommand object at 0x7f1fbc0efbe0>> to 22864
Running /home/ian/.local/share/lutris/runners/wine/tkg-4.1-x86_64/bin/wine /home/ian/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/Steam.exe -no-cef-sandbox -console
Traceback (most recent call last):
  File "/usr/bin/lutris-wrapper", line 126, in <module>
    main()
  File "/usr/bin/lutris-wrapper", line 102, in main
    returncode = subprocess.run(args).returncode
AttributeError: 'module' object has no attribute 'run'
DEBUG    2019-03-29 17:23:12,009 [command.on_stop:152]:The process has terminated with code 256
DEBUG    2019-03-29 17:23:12,010 [command.stop:235]:Management process looks dead already.
DEBUG    2019-03-29 17:23:12,010 [command.stop:247]:logger already detached
```

**Comment by IanTrudel** [comment]
A solution is provided on stack overflow but I am not sure where the code goes.

```python
def run(*popenargs, input=None, check=False, **kwargs):
    if input is not None:
        if 'stdin' in kwargs:
            raise ValueError('stdin and input arguments may not both be used.')
        kwargs['stdin'] = subprocess.PIPE

    process = subprocess.Popen(*popenargs, **kwargs)
    try:
        stdout, stderr = process.communicate(input)
    except:
        process.kill()
        process.wait()
        raise
    retcode = process.poll()
    if check and retcode:
        raise subprocess.CalledProcessError(
            retcode, process.args, output=stdout, stderr=stderr)
    return retcode, stdout, stderr
```
Reference: https://stackoverflow.com/questions/40590192/getting-an-error-attributeerror-module-object-has-no-attribute-run-while

**Comment by Saladin1812** [comment]
https://stackoverflow.com/questions/40590192/getting-an-error-attributeerror-module-object-has-no-attribute-run-while

Yes its problem with python 3.4 the run command only supports python 3.5 and above.
ugh..

**Comment by IanTrudel** [comment]
So how did you get Lutris 5.0 working? The symlink goes to version 3.4.

**Comment by Saladin1812** [comment]
the previous 4.x lutris versions also use python 3.4 on CentOS that is why we create symlink or move the package. I think then this cant be helped if lutris scripts do not support python 3.4 We have to wait for RHEL 8 or else install 3.5 or future versions manually which will be a pain.

**Comment by Saladin1812** [comment]
I will add manualy adding python version tommorow, so I will add directly for python 3.7 so symlink will also wont be needed.

**Comment by IanTrudel** [comment]
Alright, let me know!

**Comment by Saladin1812** [comment]
But then there is one more problem that all the python dependencies needed to be available for python 3.7 which have to be installed by pip. Gobject PyYAML pillow and others so this wont be much of an rpm to be honest.

**Comment by IanTrudel** [comment]
Python 3.6 is available on yum though. Might try our luck with this one.

**Comment by Saladin1812** [comment]
Yes i found it, it requires a third party repository tho @BackOrder

**Comment by Saladin1812** [comment]
Hi I created new RPM and instructions follow readme and tell if its working its working for me using python 3.6 ! @BackOrder

**Comment by Saladin1812** [comment]
currently testing battlenet
![Screenshot from 2019-03-30 13-00-12](https://user-images.githubusercontent.com/40650341/55273049-dcfef780-52eb-11e9-931b-dcf4cecea514.png)

**Comment by Saladin1812** [comment]
![Screenshot from 2019-03-30 14-14-31](https://user-images.githubusercontent.com/40650341/55273866-dc1f9300-52f6-11e9-9432-cb355db5804b.png)

the wine error is no more..things seems good

**Comment by jatin-cbs** [comment]
Its working for me i will instead use EPEL repo instead of IUS so that this wont be required wait

**Comment by jatin-cbs** [comment]
IUS is important epel one is still in testing this is the only way. But i think its not much of a pain tho :)

**Comment by jatin-cbs** [comment]
it worked like a charm :) i will close the issue if its confirmed.. follow the new RPM instruction it uses 3.6 :)

**Comment by IanTrudel** [comment]
Why doesn't it use EPEL repo? The repo you are recommending is conflicting with my Python 3.6 installation. The packages are slightly named differently and so they cannot replace one another. IUS Community adds a "u" at the end of the package name, such as python36u instead of python36. `--skip-broken` is not working either.

```
--> Traitement de la dépendance : python36u-pip pour le paquet : lutris-0.5.1.2-1.el7.x86_64
--> Traitement de la dépendance : python36u-devel pour le paquet : lutris-0.5.1.2-1.el7.x86_64
--> Résolution des dépendances terminée
Erreur : Paquet : lutris-0.5.1.2-1.el7.x86_64 (/lutris-0.5.1.2-1.el7.x86_64)
             Requiert : python36u-devel
Erreur : Paquet : lutris-0.5.1.2-1.el7.x86_64 (/lutris-0.5.1.2-1.el7.x86_64)
             Requiert : python36u-pip
Erreur : Paquet : lutris-0.5.1.2-1.el7.x86_64 (/lutris-0.5.1.2-1.el7.x86_64)
             Requiert : python36u
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème

** 1 problèmes RPMDB préexistants trouvés, la sortie de « yum check » est la suivante :
libgcc-9.0.1-0.4.fc30.i686 est un doublon de libgcc-4.8.5-36.el7.x86_64
```

```
Transaction check error:
  file /usr/bin/python3.6 from install of python36u-3.6.7-1.ius.centos7.x86_64 conflicts with file from package python36-3.6.6-2.el7.x86_64
```

**Comment by Saladin1812** [comment]
Epel repo actually has a bug of gobject, its ok to fix this

sudo gedit /etc/yum.repos.d/epel.repo 
And add this line at the end of the first paragraph (block of code)

exclude=python36*

And then update the rpms

sudo yum update

**Comment by Saladin1812** [comment]
Epel repo python36-gobject is actually in epel testing currently so we cant use that it wont work i tested it.. Just do this then conflict will be stopped..

**Comment by IanTrudel** [comment]
Alright, I removed Python36 from EPEL and now installed from IUS Community. Lutris installs with the proper dependencies. There are still a few problems though. `update-alternatives --set python3 /usr/bin/python3.6` didn't update the default python3. Do we still need to use the symlink?

**Comment by Saladin1812** [comment]
This should update the python3.. 

python3 --version

What is the output ?

**Comment by IanTrudel** [comment]
Yes, it _should_ but it didn't. I already had check the version.

```
python3 --version
Python 3.4.9
```

Also, `pip3.6` is unavailable but you could replace it in the README with `python3.6 -m pip install Pillow PyGObject evdev PyYAML requests`.

**Comment by Saladin1812** [comment]
sudo yum install python36u-pip

Is it installed ?

**Comment by IanTrudel** [comment]
```
yum list installed | grep -i python36
python36u.x86_64                       3.6.7-1.ius.centos7            @ius      
python36u-devel.x86_64                 3.6.7-1.ius.centos7            @ius      
python36u-libs.x86_64                  3.6.7-1.ius.centos7            @ius      
python36u-pip.noarch                   9.0.1-1.ius.centos7            @ius      
python36u-setuptools.noarch            39.0.1-1.ius.centos7           @ius    
```

**Comment by Saladin1812** [comment]
sudo update-alternatives --config python

Use this command it will prompt you 2 options enter the desired number.. Then check python version

**Comment by Saladin1812** [comment]
sorry replace python with python3

**Comment by Saladin1812** [comment]
sudo update-alternatives --config python3

**Comment by IanTrudel** [comment]
Not working, update-alternatives keeps returning error code 2. The only way I got this working is by removing the symlink and create one that points out to python3.6. :(

**Comment by IanTrudel** [comment]
The good news is that once I had manually symlink python3.6 with python3, Lutris is working and wine is running. We have few small things to fix but you did a really good job!

**Comment by Saladin1812** [comment]
Thanks, the issue of icons missing is not distro specific it even on KDE neon 5.1.3 , which will be fixed all tho I will put this in readme that if this returns error code then to create symlink.. Thanks for the help 😊

**Comment by Saladin1812** [comment]
@BackOrder

The error code was fixed by

sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2

This was because it isnt able to find this alternative.

**Comment by IanTrudel** [comment]
> @BackOrder
> 
> The error code was fixed by
> 
> sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
> 
> This was because it isnt able to find this alternative.

This is not working here. It still won't update the symlink to 3.6.

**Comment by Saladin1812** [comment]
@BackOrder after this command again do the set command.

**Comment by Saladin1812** [comment]
See the readme

**Comment by IanTrudel** [comment]
Hmmmm. Now I am getting a strange error. This is before reaching the second command line that you suggested.

> update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
> the primary link for python3 must be /usr/bin/python

**Comment by Saladin1812** [comment]
sudo update-alternatives --install /usr/bin/python python3 /usr/bin/python3.6 2

**Comment by Saladin1812** [comment]
Then set command

**Comment by Saladin1812** [comment]
And in future I dont think you have to set the python3 or python point to 3.6, we had to do this because our python and python3 was actually with python3.4 before can u tell me what symlink you used I think I include that in readme instead of update alternatives so it works on all systems and dont have to figure out python or python3. for casual user this would be a headache.

**Comment by Saladin1812** [comment]
and what if i simply create a .sh script that execute all the commands it will be easier for a average user.

**Comment by IanTrudel** [comment]
```
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2

sudo update-alternatives --install /usr/bin/python python3 /usr/bin/python3.6 2

sudo update-alternatives --set python3 /usr/bin/python3.6
```

No luck with the new instructions. Alternatively, if all fails, you could suggest to simply `rm /usr/bin/python3` and `ln -s /usr/bin/python3.6 /usr/bin/python3`. A script might be helpful too.

**Comment by IanTrudel** [comment]
> sudo update-alternatives --install /usr/bin/python python3 /usr/bin/python3.6 2

Unfortunately, this command breaks yum. Had to revert it to 2.7.

```
yum update
  File "/bin/yum", line 30
    except KeyboardInterrupt, e:
                            ^
```

**Comment by Saladin1812** [comment]
Ok then for me it was /usr/bin/python3 so it didnt break it. I will follow symlink instrctions thanks.. I am working on a sh script so this all becomes easier.

**Comment by Saladin1812** [comment]
The icon bug is fixed @BackOrder 
I didnt do anything tho, it was an update which solved it. 
![Screenshot from 2019-04-12 02-41-10](https://user-images.githubusercontent.com/40650341/55993376-8f5f9300-5ccc-11e9-8a32-c2120b25cf4b.png)

**Comment by IanTrudel** [comment]
Thank you for keeping me updated. :)
